-- Migration: Add tags array to films table for auto-tagging

ALTER TABLE public.films
ADD COLUMN IF NOT EXISTS tags TEXT[] DEFAULT '{}';

CREATE INDEX IF NOT EXISTS idx_films_tags ON public.films USING GIN (tags);

COMMENT ON COLUMN public.films.tags IS 'Array of semantic tags generated by AI upon video upload';
